version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - JwtConfig__Key=w5kXVM5xqRJg2mVtq64Qx74GZu9uuJe7fQFpCGUguG27m4yTpLpENK1FEyKDM9LG
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=diflenhub
      - MYSQL_LOGIN=root
      - MYSQL_PASSWORD=12345

