name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x
      - run: dotnet publish -c Release -o ./publish
      - uses: ChristopheLav/iis-deploy@v1
        with:
          msdeploy-service-url: https://${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PORT }}
          website-name: ${{ secrets.SERVER_SITE }}
          msdeploy-username: ${{ secrets.SERVER_LOGIN }}
          msdeploy-password: ${{ secrets.SERVER_PASSWORD }}
          source-path: ./publish
